package nero:extension@0.1.0-draft;

world imports {
    import wasi:http/outgoing-handler@0.2.7;
    import wasi:logging/logging@0.1.0-draft;
    @unstable(feature = extension-keyvalue-ttl)
    include nero:keyvalue-ttl/imports@0.1.0-draft;

    @unstable(feature = extension-portal)
    include nero:portal/imports@0.1.0-draft;
}

world extension {
    include imports;
    export extractor;
}
